using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Runtime state of every grid cell. One instance lives in the scene (on the Station root).
/// Tracks occupancy, reservations, and gaylord references.
/// Provides traversability queries used by Pathfinder and AMRController.
/// </summary>
public class GridMap : MonoBehaviour
{
    [Tooltip("Assign the StationGridData asset generated by the grid builder.")]
    public StationGridData gridData;

    // ── Runtime state ──────────────────────────────────────────────────────
    private CellState[,] _states; // [row0, col0]

    // ── Lifecycle ──────────────────────────────────────────────────────────

    void Awake()
    {
        if (gridData == null)
        {
            Debug.LogError("GridMap: gridData not assigned.", this);
            return;
        }
        _states = new CellState[gridData.rows, gridData.cols];
        foreach (var cell in gridData.AllCells)
            _states[cell.row - 1, cell.col - 1] = new CellState { definition = cell };
    }

    // ── Public API ─────────────────────────────────────────────────────────

    public CellState GetState(int row, int col)
    {
        if (!InBounds(row, col)) return null;
        return _states[row, col];
    }

    public CellState GetState(Vector2Int idx) => GetState(idx.x, idx.y);

    /// <summary>
    /// Can a robot enter this cell?
    /// <paramref name="loaded"/> true means the robot is carrying a gaylord.
    /// </summary>
    public bool IsTraversable(int row, int col, bool loaded)
    {
        if (!InBounds(row, col)) return false;
        var s = _states[row, col];
        if (s.definition.isNoRobot) return false;

        switch (s.definition.cellType)
        {
            case CellType.Corridor:
            case CellType.SortChute:
            case CellType.EmptyBuffer:
            case CellType.FeederQueue:
            case CellType.Staging:
            case CellType.Charging:
                return true;

            case CellType.Storage:
                // Loaded robots cannot enter storage slots
                return !loaded;

            default:
                return false;
        }
    }

    public bool IsTraversable(Vector2Int idx, bool loaded) =>
        IsTraversable(idx.x, idx.y, loaded);

    /// <summary>Reserve a cell for a robot. Returns false if already reserved by another robot.</summary>
    public bool TryReserve(int row, int col, AMRController robot)
    {
        if (!InBounds(row, col)) return false;
        var s = _states[row, col];
        if (s.reservedBy != null && s.reservedBy != robot) return false;
        s.reservedBy = robot;
        return true;
    }

    public bool TryReserve(Vector2Int idx, AMRController robot) =>
        TryReserve(idx.x, idx.y, robot);

    /// <summary>Release a reservation. No-op if this robot does not own the reservation.</summary>
    public void Release(int row, int col, AMRController robot)
    {
        if (!InBounds(row, col)) return;
        var s = _states[row, col];
        if (s.reservedBy == robot) s.reservedBy = null;
    }

    public void Release(Vector2Int idx, AMRController robot) =>
        Release(idx.x, idx.y, robot);

    /// <summary>Mark a cell as occupied by a gaylord.</summary>
    public void SetOccupied(int row, int col, GameObject gaylord)
    {
        if (!InBounds(row, col)) return;
        var s = _states[row, col];
        s.occupied = gaylord != null;
        s.gaylord  = gaylord;
    }

    public void SetOccupied(Vector2Int idx, GameObject gaylord) =>
        SetOccupied(idx.x, idx.y, gaylord);

    /// <summary>Returns all occupied storage slot cells and their gaylord references.</summary>
    public List<(Vector2Int cell, GameObject gaylord)> GetOccupiedStorageSlots()
    {
        var result = new List<(Vector2Int, GameObject)>();
        for (int r = 0; r < gridData.rows; r++)
        for (int c = 0; c < gridData.cols; c++)
        {
            var s = _states[r, c];
            if (s.definition.cellType == CellType.Storage && s.occupied)
                result.Add((new Vector2Int(r, c), s.gaylord));
        }
        return result;
    }

    // ── World position helpers ─────────────────────────────────────────────

    /// <summary>Cell width along the X axis (metres). Set by StationGridBuilder.</summary>
    public float cellWidth = 1.4f;

    /// <summary>Cell depth along the Z axis (metres). Set by StationGridBuilder.</summary>
    public float cellDepth = 1.2f;

    /// <summary>Returns the current cell size as a 2D vector (X width, Y depth).</summary>
    public Vector2 CellSize => new Vector2(cellWidth, cellDepth);

    /// <summary>Returns the smaller of the current cell width/depth.</summary>
    public float MinCellDimension => Mathf.Min(cellWidth, cellDepth);

    /// <summary>World-space origin — top-left corner of cell (0,0).</summary>
    public Vector3 gridOrigin = Vector3.zero;

    /// <summary>Returns the world-space centre of a grid cell (XZ plane, Y = gridOrigin.y).</summary>
    public Vector3 CellToWorld(int row, int col) =>
        gridOrigin + new Vector3((col + 0.5f) * cellWidth, 0f, -(row + 0.5f) * cellDepth);

    public Vector3 CellToWorld(Vector2Int idx) => CellToWorld(idx.x, idx.y);

    /// <summary>Snaps a world position to the nearest grid cell index.</summary>
    public Vector2Int WorldToCell(Vector3 worldPos)
    {
        Vector3 local = worldPos - gridOrigin;
        int col = Mathf.FloorToInt(local.x / cellWidth);
        int row = Mathf.FloorToInt(-local.z / cellDepth);
        return new Vector2Int(
            Mathf.Clamp(row, 0, gridData.rows - 1),
            Mathf.Clamp(col, 0, gridData.cols - 1));
    }

    // ── Private ────────────────────────────────────────────────────────────

    private bool InBounds(int row, int col) =>
        row >= 0 && row < gridData.rows && col >= 0 && col < gridData.cols;
}

/// <summary>Runtime mutable state for one grid cell.</summary>
public class CellState
{
    public CellData     definition;   // immutable parsed data
    public bool         occupied;     // a gaylord is sitting here
    public GameObject   gaylord;      // which gaylord
    public AMRController reservedBy;  // robot that has reserved this cell for its next move
}
